# Generated by Django 4.2.1 on 2023-05-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='StudData',
        ),
        migrations.RenameField(
            model_name='studdata',
            old_name='country',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='studdata',
            old_name='name',
            new_name='student',
        ),
    ]
